import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/menu";


export const metadata: Metadata = {
  title: "Origamid next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        {children}
        <Menu/>
      </body>
    </html>
  );
}
